print("Put log in slot 1")
print("Put cobble in slot 2, 15 and 16")
print("Put glass in slot 3")
turtle.up()
turtle.up()
turtle.select(2)
turtle.place()
for t=1,4 do
	turtle.turnLeft()
	turtle.forward()
	turtle.turnRight()
	turtle.place()
end
turtle.down()
turtle.place()
turtle.down()
turtle.place()
for v=1,4 do
	turtle.turnRight()
	turtle.forward()
	turtle.turnLeft()
	turtle.place()
end
turtle.up()
turtle.place()
turtle.select(3)
for w=1,2 do
	turtle.turnLeft()
	turtle.forward()
	turtle.turnRight()
	turtle.place()
end
turtle.turnLeft()
turtle.forward()
turtle.forward()
turtle.turnRight()
turtle.forward()
turtle.select(1)
turtle.placeDown()
turtle.up()
turtle.placeDown()
turtle.up()
turtle.placeDown()
turtle.forward()
turtle.down()
turtle.down()

function wall()
turtle.select(2)
for f=1,9 do
	turtle.placeDown()
	turtle.forward()
end
turtle.up()
turtle.placeDown()
turtle.turnLeft()
turtle.turnLeft()
turtle.forward()
turtle.select(3)
turtle.placeDown()
turtle.forward()
turtle.placeDown()
turtle.select(2)
turtle.forward()
turtle.placeDown()
turtle.forward()
turtle.placeDown()
turtle.forward()
turtle.placeDown()
turtle.select(3)
turtle.forward()
turtle.placeDown()
turtle.forward()
turtle.placeDown()
turtle.forward()
turtle.select(2)
turtle.placeDown()
turtle.up()
turtle.turnLeft()
turtle.turnLeft()
for s=1,9 do
	turtle.placeDown()
	turtle.forward()
end
end
wall()
turtle.forward()
turtle.down()
turtle.down()
turtle.select(1)
turtle.placeDown()
turtle.up()
turtle.placeDown()
turtle.up()
turtle.placeDown()
turtle.turnRight()
turtle.forward()
turtle.down()
turtle.down()
turtle.select(16)
turtle.transferTo(2)
wall()
turtle.forward()
turtle.down()
turtle.down()
turtle.select(1)
turtle.placeDown()
turtle.up()
turtle.placeDown()
turtle.up()
turtle.placeDown()
turtle.turnRight()
turtle.forward()
turtle.down()
turtle.down()
turtle.select(15)
turtle.transferTo(2)	




