@echo off
cd C:\Users\arviwed0310\Documents\JavaScript
>>livehack.txt echo Hello...
start livehack.txt
>>livehack.txt echo Hacking proccess has been started...
>nul ping -n 1 localhost
>>livehack.txt echo Downloading virus...
>nul ping -n 1 localhost 
>>livehack.txt echo Computer infected...
>nul ping -n 1 localhost
del livehack.txt
copy Livehack.bat Livehack.bat
